// these constants are just to avoid typos
export const GET_FILMS_REQUEST = 'GET_FILMS_REQUEST';
export const GET_FILMS_SUCCES = 'GET_FILMS_SUCCES';
export const GET_FILMS_FAILURE = 'GET_FILMS_FAILURE';

export const ADD_FILM_REQUEST = 'ADD_FILM_REQUEST';
export const ADD_FILM_SUCCESS = 'ADD_FILM_SUCCESS';
export const ADD_FILM_FAILURE = 'ADD_FILM_FAILURE';

export const DELETE_FILM_REQUEST = 'DELETE_FILM_REQUEST';
export const DELETE_FILM_SUCCESS = 'DELETE_FILM_SUCCESS';
export const DELETE_FILM_FAILURE = 'DELETE_FILM_FAILURE';

export const UPDATE_FILM_REQUEST = 'UPDATE_FILM_REQUEST';
export const UPDATE_FILM_SUCCESS = 'UPDATE_FILM_SUCCESS';
export const UPDATE_FILM_FAILURE = 'UPDATE_FILM_FAILURE';