export const GET_SCREENINGS_REQUEST = 'GET_SCREENINGS_REQUEST';
export const GET_SCREENINGS_SUCCES = 'GET_SCREENINGS_SUCCES';
export const GET_SCREENINGS_FAILURE = 'GET_SCREENINGS_FAILURE';

export const ADD_SCREENING_REQUEST = 'ADD_SCREENING_REQUEST';
export const ADD_SCREENING_SUCCESS = 'ADD_SCREENING_SUCCESS';
export const ADD_SCREENING_FAILURE = 'ADD_SCREENING_FAILURE';

export const UPDATE_SCREENING_REQUEST = 'UPDATE_SCREENING_REQUEST';
export const UPDATE_SCREENING_SUCCESS = 'UPDATE_SCREENING_SUCCESS';
export const UPDATE_SCREENING_FAILURE = 'UPDATE_SCREENING_FAILURE';